version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mistakedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  web:
    build: .
    command: python nayamidic/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/server
    ports:
      - "8000:8000"
    depends_on:
      - db