# Generated by Django 3.2.13 on 2022-06-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistake', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='delete_flag',
            field=models.IntegerField(default=0),
        ),
    ]
