# Generated by Django 3.2.13 on 2022-06-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistake', '0004_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
