# Generated by Django 3.2.13 on 2023-04-01 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistake', '0009_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_mixed',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_negative',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_neutral',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_positive',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medi/'),
        ),
    ]
