# Generated by Django 4.1.5 on 2023-01-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistake', '0009_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medi/'),
        ),
    ]
